nombre: GitHub Actions Demo 
nombre-ejecutar: ${{ github.actor }} estÃ¡ probando GitHub Actions ğŸš€ 
en: [push] 
trabajos: 
  Explore-GitHub-Actions: 
    se ejecuta en: ubuntu-latest 
    pasos: 
      - ejecutar: echo "ğŸ‰ El trabajo se activÃ³ automÃ¡ticamente mediante un evento ${{ github.event_name }}." 
      - ejecutar: echo "ğŸ§ Â¡Este trabajo ahora se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado por GitHub!" 
      - ejecutar: echo "ğŸ” El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}." 
      - nombre: Consultar repositorio cÃ³digo 
        usos: acciones/checkout@v4 
      - ejecutar: echo "ğŸ’¡ El repositorio ${{ github.repository }} se ha clonado en el ejecutor." 
      - run: echo "ğŸ–¥ï¸ El flujo de trabajo ahora estÃ¡ listo para probar su cÃ³digo en el ejecutor". 
      - name: Lista de archivos en el repositorio. 
        run: | 
          ls ${{ github.workspace }}. 
      - run: echo "ğŸ El estado de este trabajo es ${{ job.status }}".
